
name: push
run-name: ${{ github.actor }} pushed on any branch
on: [push]
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build apk
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: volume_control_android-${{ github.ref_name }}.apk
