
name: meh
run-name: ${{ github.actor }} is building on MS dime.
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: my-app.apk
          browserstack-upload: false
          #browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          #browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          ruby-version: "2.7.5"
          bundler-version: "2.3.26"
          fastlane-env: "debug"
